name: Build and Deploy App # Имя пайплайна

on:
  push:
    branches: [ main ] # Триггер при пуше в main

jobs:
  build: # 1. CI-Задача: Сборка и Отправка
    runs-on: ubuntu-latest
    outputs:
      image_tag_sha: ${{ steps.vars.outputs.short_sha }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4


      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile

      - name: Set short git SHA
        id: vars
        run: echo "short_sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
     
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    
      - name: Build and Push Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/my-hello-app:${{ steps.vars.outputs.short_sha }} 

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: ${{ secrets.DOCKERHUB_USERNAME }}/my-hello-app:latest
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

  deploy:
    needs: build # Ждем, пока 'build' завершится
    runs-on: ubuntu-latest
    steps:
      # (1) Получаем код, он нам не нужен, но это хорошая практика
      - name: Checkout code
        uses: actions/checkout@v4

      # (2) Устанавливаем kubectl на "бегуна" GitHub
      - name: Set up kubectl
        uses: azure/setup-kubectl@v4
        # можно указать 'version: v1.29.0' или оставить latest

      # (3) КЛЮЧЕВОЙ ШАГ: Логинимся в K8s
      # Этот Action берет секрет и превращает его в файл ~/.kube/config
      - name: Set up K8s context
        uses: azure/k8s-set-context@v4
        with:
          # (4) Вот здесь мы говорим Action'у взять наш секрет
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBE_CONFIG }} # <-- Нам нужно будет создать этот секрет

      # (5) НАША КОМАНДА: Теперь kubectl работает по-настоящему
  #    - name: Deploy to K8s
  #      run: |
  #       echo "Deploying image ${{ secrets.DOCKERHUB_USERNAME }}/my-hello-app:${{ needs.build.outputs.image_tag_sha }}"
          
   #       kubectl set image deployment/app-deployment app-container=${{ secrets.DOCKERHUB_USERNAME }}/my-hello-app:${{ needs.build.outputs.image_tag_sha }}
          
   #       echo "Waiting for rollout to complete..."
   #       kubectl rollout status deployment/app-deployment
